version: 2

sources:
  - name: yyj_raw
    database: data-stack-338105
    schema: yyj_raw
    tables:
      - name: building_permits

models:
  - name: prep_building_permits
    meta:
      fal:
        scripts:
          - fal_scripts/send_slack_message.py
    schema: cdn_real_estate