
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'cdn_re'
version: '1.0.0'

require-dbt-version: [">=1.0.0"]
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'metrics'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# ==================
# Variable Configs
# ==================
vars:

  infinity_future: TO_DATE('9999-12-31', 'YYYY-MM-DD')
  infinity_past: TO_DATE('1970-01-01', 'YYYY-MM-DD')
  tomorrow: DATEADD('day',1,CURRENT_DATE())



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

# ==================
# Model Configs
# ==================

models:
  cdn_re:
    +database: "{{ env_var('PREP_DATABASE') }}" #PREP

    # ------------------
    # Sources
    # ------------------
    sources:
      +database: "{{ env_var('PREP_DATABASE') }}" #PREP
      +tags: ["sources"]

      open_data:
        +materialized: table
        +schema: open_data

    # ------------------
    # Common
    # ------------------
    common:
      +materialized: table
      +schema: common

    common_prep:
      +materialized: table
      +schema: common_prep





