version: 2

models:
  - name: yyj_monthly_building_permits
    columns:
      - name: issued_month
      - name: permits_requested
      - name: average_days_to_approve
      - name: average_cost_of_work